"""
********************************************************************************
*                             CNIRevelator                                     *
*                                                                              *
*  Desc:       Application langage file                                        *
*                                                                              *
*  Copyright © 2018-2019 Adrien Bourmault (neox95)                             *
*                                                                              *
*  This file is part of CNIRevelator.                                          *
*                                                                              *
*  CNIRevelator is free software: you can redistribute it and/or modify        *
*  it under the terms of the GNU General Public License as published by        *
*  the Free Software Foundation, either version 3 of the License, or           *
*  any later version.                                                          *
*                                                                              *
*  CNIRevelator is distributed in the hope that it will be useful,             *
*  but WITHOUT ANY WARRANTY*without even the implied warranty of               *
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
*  GNU General Public License for more details.                                *
*                                                                              *
*  You should have received a copy of the GNU General Public License           *
* along with CNIRevelator. If not, see <https:*www.gnu.org/licenses/>.         *
********************************************************************************
"""
import os

import globs                        # globs.py
import critical                     # critical.py

## FRENCH LANGUAGE
french = \
{
"Please type a MRZ or open a scan"  :   "Veuillez taper une MRZ ou ouvrir un scan svp",
"Changelog : update summary"        :   "Changelog : résumé de mise à jour",
"Program version"                   :   "Version du logiciel",
"CNIRevelator Fatal Error"          :   "Erreur fatale de CNIRevelator",
"An error has occured"              :   "Une erreur s'est produite",
"Downloading"                       :   "Téléchargement de",
"Successful retrieved"              :   "Réussite du téléchargement de",
"Choose the identity document"      :   "Choisir le document d'identité",
"OCR Detection Validation"          :   "Validation de la MRZ détectée par OCR",
"Validate"                          :   "Valider",
"Validation Error"                  :   "Erreur de validation",
"The submitted MRZ contains invalid "
 "characters"                       :   "La MRZ soumise contient des caractères invalides",
"Connection"                        :   "Connexion",
"Password"                          :   "Mot de passe",
"Booting up..."                     :   "Démarrage",
"CNIRevelator Fatal Eror"           :   "Erreur Fatale de CNIRevelator",
"CNIRevelator crashed because a "
"fatal error occured. View log for "
"more infos and please open "
"an issue on Github"                :   "CNIRevelator s'est arrêté car une erreur fatale s'est produite. Consultez le journal pour plus d'informations et ouvrez s'il vous plaît un ticket sur Github.",
"Would you like to open the "
"log file ?"                        :   "Souhaitez-vous ouvrir le fichier de log ?",
"Would you like to open an issue "
"on Github to report this bug ?"    :   "Souhaitez-vous ouvrir un ticket sur Github pour signaler ce bogue?",
"Starting..."                       :   "Lancement...",
"Informations about the current "
"document"                          :   "Informations sur la pièce d'identité",
"IDLE"                              :   "EN ATTENTE",
"Status"                            :   "Statut",
"Name"                              :   "Nom",
"Birth date"                        :   "Date de naissance",
"Issue date"                        :   "Date de délivrance",
"Expiration date"                   :   "Date d'expiration",
"Sex"                               :   "Sexe",
"Issuing country"                   :   "Pays émetteur",
"Nationality"                       :   "Nationalité",
"Registration"                      :   "Immatriculation",
"Document number"                   :   "N° de document",
"Unknown"                           :   "Inconnu(e)",
"Display and processing of "
"documents"                         :   "Affichage et traitement de documents",
"Complete MRZ capture terminal"     :   "Terminal de saisie de MRZ complète",
"Quick entry terminal (731)"        :   "Terminal de saisie rapide (731)",
"Monitor"                           :   "Moniteur",
"New"                               :   "Nouveau",
"Open scan..."                      :   "Ouvrir scan...",
"Quit"                              :   "Quitter",
"File"                              :   "Fichier",
"Settings"                          :   "Paramètres",
"Keyboard commands"                 :   "Commandes au clavier",
"Report a bug"                      :   "Signaler un problème",
"About CNIRevelator"                :   "A propos de CNIRevelator",
"Help"                              :   "Aide",
"OCR module error"                  :   "Erreur du module OCR",
"The OCR module located at {} "
"can not be found or corrupted. "
"It will be reinstalled at "
"the next run"                      :   "Le module OCR localisé en {} est introuvable ou corrompu. Il sera réinstallé à la prochaine exécution",
"The Tesseract module "
"encountered a problem: {}"         :   "Le module Tesseract a rencontré un problème : {}",
"Tesseract error : {}. "
"Will be reinstallated"             :   "Erreur de Tesseract : {}. Le module sera réinstallé",
"Document detected: {}\n"           :   "Document detecté : {}\n",
"Document detected again: {}\n"     :   "Document re-detecté : {}\n",
"Character not accepted !\n"        :   "Caractère non accepté !\n",
"Open a scan of document..."        :   "Ouvrir un scan de document...",
"OpenCV error (image processing)"   :   "Erreur OpenCV (traitement d'images)",
"A critical error has occurred in "
"the OpenCV image processing "
"manager used by CNIRevelator, the "
"application will reset itself"     :   "Une erreur critique s'est produite dans le gestionnaire de traitement d'images OpenCV utilisé par CNIRevelator. L'application va se réinitialiser",
"ABOUT"                             :   'Version du logiciel : CNIRevelator ' + globs.verstring_full + '\n\n'
                                        "Copyright © 2018-2019 Adrien Bourmault (neox95)" + "\n\n"
                                        "CNIRevelator est un logiciel libre : vous avez le droit de le modifier et/ou le distribuer "
                                        "dans les termes de la GNU General Public License telle que publiée par "
                                        "la Free Software Foundation, dans sa version 3 ou "
                                        "ultérieure. " + "\n\n"
                                        "CNIRevelator est distribué dans l'espoir d'être utile, sans toutefois "
                                        "impliquer une quelconque garantie de "
                                        "QUALITÉ MARCHANDE ou APTITUDE À UN USAGE PARTICULIER. Référez vous à la "
                                        "GNU General Public License pour plus de détails à ce sujet. "
                                        "\n\n"
                                        "Vous devriez avoir reçu une copie de la GNU General Public License "
                                        "avec CNIRevelator. Si cela n'est pas le cas, jetez un oeil à <https://www.gnu.org/licenses/>. "
                                        "\n\n"
                                        "Le module d'OCR Tesseract 4.0 est soumis à l'Apache License 2004."
                                        "\n\n"
                                        "Les bibliothèques python et l'environnement Anaconda 3 sont soumis à la licence BSD 2018-2019."
                                        "\n\n"
                                        "Le code source de ce programme est disponible sur Github à l'adresse <https://github.com/neox95/CNIRevelator>.\n"
                                        "Son fonctionnement est conforme aux normes et directives du document 9303 de l'OACI régissant les documents de voyages et d'identité." + '\n\n'
                                        " En cas de problèmes ou demande particulière, ouvrez-y une issue ou bien envoyez un mail à neox@os-k.eu !\n\n",

"KEYBHELP"                          :   "Terminal de saisie rapide (731) : \n\n"
                                        "Caractères autorisés : Alphanumériques en majuscule et le caractère '<'. Pas de minuscules ni caractères spéciaux, autrement la somme est mise à zéro \n\n"
                                        "Calculer résultat :\t\t\tTouche Ctrl droite \n"
                                        "Copier :\t\t\t\tCtrl-C \n"
                                        "Coller :\t\t\t\tCtrl-V \n"
                                        "\n\n"
                                        "Terminal de saisie MRZ complète : \n\n"
                                        "Caractères autorisés : Alphanumériques en majuscule et le caractère '<'. Pas de minuscules ni caractères spéciaux, autrement la somme est mise à zéro \n\n"
                                        "Calculer résultat :\t\t\tTouche Ctrl droite \n"
                                        "Compléter champ :\t\t\tTouche Tab \n"
                                        "Copier :\t\t\t\tCtrl-C \n"
                                        "Coller :\t\t\t\tCtrl-V \n"
                                        "Forcer une nouvelle détection du document :\tEchap\n",

"CHANGELOG"                         :   "Version 3.1.2 \nMise-à-jour mineure avec les progressions suivantes :\n- Montée de version de Tesseract OCR : 5.0\n\n" + \
"Version 3.1.1 \nMise-à-jour mineure avec les progressions suivantes :\n- Correction d'un bug sévère du système de mise à jour\n\n" + \
"Version 3.1.0 \nMise-à-jour majeure avec les progressions suivantes :\n- Modifications cosmétiques de l'interface utilisateur\n- Stabilisation des changements effectués sur la version mineure 3.0 : interface utilisateur, OCR, VISA A et B, logging\n- Rationalisation du système de langues\n- Ajout des canaux de mise-à-jour\n\n" + \
"Version 3.0.8 finale\nCorrectif : bug du système de mise-à-jour'\n\n" + \
"Version 3.0.6 \nMise-à-jour mineure avec les corrections suivantes :\n- Changement de l'apparence du launcher de l'application\n- Améliorations de l'interface, notamment de la stabilité\n- Ajout de la signature numérique de l'exécutable\n\n" + \
"Version 3.0.7 finale\nMise-à-jour majeure avec les corrections suivantes :\n- Refonte de l'interface utilisateur\n- Fonction OCR intégrée à l'application avec support des TIFF et JPEG\n- Corrections d'erreurs sur le traitement des VISA de type A et B, ainsi que les titres de séjour\n\n" + \
"Version 3.0.6 \nMise-à-jour mineure avec les corrections suivantes :\n- Changement de l'apparence du launcher de l'application\n- Améliorations de l'interface, notamment de la stabilité\n- Ajout de la signature numérique de l'exécutable\n\n" + \
"Version 3.0.5 \nMise-à-jour mineure avec les corrections suivantes :\n- Changement de l'icône de l'exécutable afin de refléter le changement de version majeur accompli en 3.0\n\n" + \
"Version 3.0.4 \nMise-à-jour mineure avec les corrections suivantes :\n- Correction d'un bug affectant le système de mise-à-jour\n\n" + \
"Version 3.0.3 \nMise-à-jour mineure avec les corrections suivantes :\n- Correction d'un bug affectant le changelog\n- Correction d'une erreur avec la touche Suppr Arrière et Suppr causant une perte de données\n\n" + \
"Version 3.0.2 \nMise-à-jour mineure avec les corrections suivantes :\n- Changement d'icône de l'exécutable\n- Correction d'un bug affectant le logging\n- Correction d'un bug affectant la détection de documents\n- Et autres modifications mineures\n\n" + \
"Version 3.0.1 \nMise-à-jour majeure avec les corrections suivantes :\n- Renouvellement de la signature numérique de l'exécutable\n- Amélioration de présentation du log en cas d'erreur\n- Refonte totale du code source et désobfuscation\n- Téléchargements en HTTPS fiables avec somme de contrôle\n- Nouveaux terminaux d'entrées : un rapide (731) et un complet\n- Détection des documents améliorée, possibilité de choix plus fin\nEt les regressions suivantes :\n- Suppression temporaire de la fonction de lecture OCR. Retour planifié pour une prochaine version",

"Document Review: {}\n\n"           :   "Examen du document : {}\n\n",
"Calculated {} [facultative]\n"     :   "Checksum position {}: Lu {} VS Calculé {} [facultatif]\n",
"Checksum position {}: Lu {} VS "
"Calculated {}\n"                   :   "Checksum position {}: Lu {} VS Calculé {}\n",
"COMPLIANT"                         :   "CONFORME",
"IMPROPER"                          :   "NON CONFORME",
"Installing the updates"            :   "Installation des mises-à-jour",
"Verifying download..."             :   "Vérification du téléchargement ...",
"Preparing installation..."         :   "Préparation de l'installation",
"Success !"                         :   "Installation terminée !",
"Launching the new version..."      :   "Lancement de la nouvelle version...",
"Credentials Error. No effective "
"update !"                          :   "Identifiants incorrects. Pas de mise-à-jour !",
"Deleting old version"              :   "Suppression de l'ancienne version",
'Software is up-to-date !'          :   "Logiciel à jour !",
"An error occured. "
"No effective update !"             :   "Une erreur s'est produite. Pas de mise-à-jour !",
"Shortcut creation"                 :   "Création de raccourci",
"Would you like to create/update "
"the shortcut for CNIRevelator "
"on your desktop ?"                 :   "Souhaitez vous créer/mettre à jour le raccourci pour CNIRevelator sur votre bureau ?",
"The file you provided is "
"not found : {}"                    :   "Fichier transmis non trouvé : {}",
"Update options"                    :   "Options de mise-à-jour",
"Language"                          :   "Langue",
"Show Changelog"                    :   "Résumé de mise-à-jour",
"Please choose your language : "    :   "Merci de choisir votre langue : ",
"Please choose your update "
"channel : "                        :   "Merci de choisir votre canal de mise-à-jour : ",
"Passeport"                         :   "Passeport",
"Carte-passeport"                   :   "Carte-passeport",
"Titre d'identité/de voyage"        :   "Titre d'identité/de voyage",
"Certificat de membre d'équipage"   :   "Certificat de membre d'équipage",
"Visa de type A"                    :   "Visa de type A",
"Visa de type B"                    :   "Visa de type B",
"Carte de séjour"                   :   "Carte de séjour",
"Pièce d'identité/de voyage"        :   "Pièce d'identité/de voyage",
"Pièce d'identité FR"               :   "Pièce d'identité FR",
"Permis de conduire"                :   "Permis de conduire",
"The file you provided is not "
"valid : {}"                        :   "Le fichier transmis n'est pas valide : {}",

"LANDCODE2"                         :   {
                                            'AW': 'Aruba',
                                            'AF': 'Afghanistan',
                                            'AO': 'Angola',
                                            'AI': 'Anguilla',
                                            'AL': 'Albanie',
                                            'AD': 'Andorre',
                                            'AE': 'Emirats arabes unis',
                                            'AR': 'Argentine',
                                            'AM': 'Arménie',
                                            'AS': 'Samoa américaines',
                                            'AQ': 'Antarctique',
                                            'TF': 'Terres australes et antarctiques françaises',
                                            'AG': 'Antigua-et-Barbuda',
                                            'AU': 'Australie',
                                            'AT': 'Autriche',
                                            'AZ': 'Azerbaidjan',
                                            'BI': 'Burundi',
                                            'BE': 'Belgique',
                                            'BJ': 'Benin',
                                            'BQ': 'Pays-Bas caribéens',
                                            'BF': 'Burkina Faso',
                                            'BD': 'Bangladesh',
                                            'BG': 'Bulgarie',
                                            'BH': 'Bahrein',
                                            'BS': 'Bahamas',
                                            'BA': 'Bosnie-Herzegovine',
                                            'BL': 'Saint-Barthélemy',
                                            'BY': 'Bielorussie',
                                            'BZ': 'Belize',
                                            'BM': 'Bermudes',
                                            'BO': 'Bolivie',
                                            'BR': 'Brésil',
                                            'BB': 'Barbade',
                                            'BN': 'Brunei',
                                            'BT': 'Bhoutan',
                                            'BW': 'Botswana',
                                            'CF': 'République Centrafricaine',
                                            'CA': 'Canada',
                                            'CC': 'Îles Cocos',
                                            'CH': 'Suisse',
                                            'CL': 'Chili',
                                            'CN': 'Chine',
                                            'CI': "Côte d'Ivoire",
                                            'CM': 'Cameroun',
                                            'CD': 'Congo (République démocratique)',
                                            'CG': 'Congo (République)',
                                            'CK': 'Îles Cook',
                                            'CO': 'Colombie',
                                            'KM': 'Comores',
                                            'CV': 'Cap-Vert',
                                            'CR': 'Costa Rica',
                                            'CU': 'Cuba',
                                            'CW': 'Curaçao',
                                            'CX': 'Île Christmas',
                                            'KY': 'Caimans',
                                            'CY': 'Chypre',
                                            'CZ': 'Tchéquie',
                                            'DE': 'Allemagne',
                                            'DJ': 'Djibouti',
                                            'DM': 'Dominique',
                                            'DK': 'Danemark',
                                            'DO': 'République dominicaine',
                                            'DZ': 'Algérie',
                                            'EC': 'Equateur',
                                            'EG': 'Egypte',
                                            'ER': 'Erythrée',
                                            'EH': 'Sahara occidental',
                                            'ES': 'Espagne',
                                            'EE': 'Estonie',
                                            'ET': 'Ethiopie',
                                            'FI': 'Finlande',
                                            'FJ': 'Fidji',
                                            'FK': 'Îles Malouines',
                                            'FR': 'France',
                                            'FO': 'Féroé',
                                            'FM': 'Micronésie',
                                            'GA': 'Gabon',
                                            'GB': 'Royaume-Uni',
                                            'GE': 'Géorgie',
                                            'GG': 'Guernesey',
                                            'GH': 'Ghana',
                                            'GI': 'Gibraltar',
                                            'GN': 'Guinée',
                                            'GP': 'Guadeloupe',
                                            'GM': 'Gambie',
                                            'GW': 'Guinée-Bissau',
                                            'GQ': 'Guinée équatoriale',
                                            'GR': 'Grèce',
                                            'GD': 'Grenade',
                                            'GL': 'Groenland',
                                            'GT': 'Guatemala',
                                            'GF': 'Guyane',
                                            'GU': 'Guam',
                                            'GY': 'Guyana',
                                            'HK': 'Hong Kong',
                                            'HN': 'Honduras',
                                            'HR': 'Croatie',
                                            'HT': 'Haïti',
                                            'HU': 'Hongrie',
                                            'ID': 'Indonésie',
                                            'IM': 'Île de Man',
                                            'IN': 'Inde',
                                            'IO': "Territoire britannique de l'océan Indien",
                                            'IE': 'Irlande',
                                            'IR': 'Irak',
                                            'IQ': 'Iran',
                                            'IS': 'Islande',
                                            'IL': 'Israël',
                                            'IT': 'Italie',
                                            'JM': 'Jamaïque',
                                            'JE': 'Jersey',
                                            'JO': 'Jordanie',
                                            'JP': 'Japon',
                                            'KZ': 'Kazakhstan',
                                            'KE': 'Kenya',
                                            'KG': 'Kirghizistan',
                                            'KH': 'Cambodge',
                                            'KI': 'Kiribati',
                                            'KN': 'Saint-Christophe-et-Niévès',
                                            'KR': 'Corée du Sud',
                                            'KW': 'Koweït',
                                            'LA': 'Laos',
                                            'LB': 'Liban',
                                            'LR': 'Liberia',
                                            'LY': 'Libye',
                                            'LC': 'Sainte-Lucie',
                                            'LI': 'Liechtenstein',
                                            'LK': 'Sri Lanka',
                                            'LS': 'Lesotho',
                                            'LT': 'Lituanie',
                                            'LU': 'Luxembourg',
                                            'LV': 'Lettonie',
                                            'MO': 'Macao',
                                            'MF': 'Sint-Maarten',
                                            'MA': 'Maroc',
                                            'MC': 'Monaco',
                                            'MD': 'Moldavie',
                                            'MG': 'Madagascar',
                                            'MV': 'Maldives',
                                            'MX': 'Mexique',
                                            'MH': 'Marshall',
                                            'MK': 'Macedoine',
                                            'ML': 'Mali',
                                            'MT': 'Malte',
                                            'MM': 'Birmanie',
                                            'ME': 'Monténégro',
                                            'MN': 'Mongolie',
                                            'MP': 'Îles Mariannes du Nord',
                                            'MZ': 'Mozambique',
                                            'MR': 'Mauritanie',
                                            'MS': 'Montserrat',
                                            'MQ': 'Martinique',
                                            'MU': 'Maurice',
                                            'MW': 'Malawi',
                                            'MY': 'Malaisie',
                                            'YT': 'Mayotte',
                                            'NA': 'Namibie',
                                            'NC': 'Nouvelle-Calédonie',
                                            'NE': 'Niger',
                                            'NF': 'Île Norfolk',
                                            'NG': 'Nigeria',
                                            'NI': 'Nicaragua',
                                            'NU': 'Niue',
                                            'NL': 'Pays-Bas',
                                            'NO': 'Norvège',
                                            'NP': 'Nepal',
                                            'NR': 'Nauru',
                                            'NZ': 'Nouvelle-Zélande',
                                            'OM': 'Oman',
                                            'PK': 'Pakistan',
                                            'PA': 'Panama',
                                            'PN': 'Îles Pitcairn',
                                            'PE': 'Pérou',
                                            'PH': 'Philippines',
                                            'PW': 'Palaos',
                                            'PG': 'Papouasie-Nouvelle-Guinée',
                                            'PL': 'Pologne',
                                            'PR': 'Porto Rico',
                                            'KP': 'Corée du Nord',
                                            'PT': 'Portugal',
                                            'PY': 'Paraguay',
                                            'PS': 'Palestine',
                                            'PF': 'Polynésie française',
                                            'QA': 'Qatar',
                                            'RE': 'Réunion',
                                            'RO': 'Roumanie',
                                            'RU': 'Russie',
                                            'RW': 'Rwanda',
                                            'SA': 'Arabie saoudite',
                                            'SD': 'Soudan',
                                            'SN': 'Sénégal',
                                            'SG': 'Singapour',
                                            'GS': 'Georgie du Sud-et-les iles Sandwich du Sud',
                                            'SH': 'Sainte-Hélène, Ascension et Tristan da Cunha',
                                            'SJ': 'Svalbard et île Jan Mayen',
                                            'SB': 'Salomon',
                                            'SL': 'Sierra Leone',
                                            'SV': 'Salvador',
                                            'SM': 'Saint-Marin',
                                            'SO': 'Somalie',
                                            'PM': 'Saint-Pierre-et-Miquelon',
                                            'RS': 'Serbie',
                                            'SS': 'Soudan du Sud',
                                            'ST': 'Sao Tomé-et-Principe',
                                            'SR': 'Suriname',
                                            'SK': 'Slovaquie',
                                            'SI': 'Slovénie',
                                            'SE': 'Suède',
                                            'SZ': 'eSwatani',
                                            'SX': 'Saint-Martin ',
                                            'SC': 'Seychelles',
                                            'SY': 'Syrie',
                                            'TC': 'Îles Turques-et-Caïques',
                                            'TD': 'Tchad',
                                            'TG': 'Togo',
                                            'TH': 'Thaïlande',
                                            'TJ': 'Tadjikistan',
                                            'TK': 'Tokelau',
                                            'TM': 'Turkmenistan',
                                            'TL': 'Timor oriental',
                                            'TO': 'Tonga',
                                            'TT': 'Trinité-et-Tobago',
                                            'TN': 'Tunisie',
                                            'TR': 'Turquie',
                                            'TV': 'Tuvalu',
                                            'TW': 'Taiwan',
                                            'TZ': 'Tanzanie',
                                            'UG': 'Ouganda',
                                            'UA': 'Ukraine',
                                            'UY': 'Uruguay',
                                            'US': 'Etats-Unis',
                                            'UZ': 'Ouzbékistan',
                                            'VA': 'Saint-Siège (État de la Cité du Vatican)',
                                            'VC': 'Saint-Vincent-et-les-Grenadines',
                                            'VE': 'Venezuela',
                                            'VG': 'Îles Vierges britanniques',
                                            'VI': 'Îles Vierges des États-Unis',
                                            'VN': 'Viêt Nam',
                                            'VU': 'Vanuatu',
                                            'WF': 'Wallis-et-Futuna',
                                            'WS': 'Samoa',
                                            'XK': 'Kosovo',
                                            'YE': 'Yémen',
                                            'ZA': 'Afrique du Sud',
                                            'ZM': 'Zambie',
                                            'ZW': 'Zimbabwe'
                                        },

"LANDCODE3"                         :   {
                                            'ABW': 'Aruba',
                                            'AFG': 'Afghanistan',
                                            'AGO': 'Angola',
                                            'AIA': 'Anguilla',
                                            'ALB': 'Albanie',
                                            'AND': 'Andorre',
                                            'ARE': 'Emirats arabes unis',
                                            'ARG': 'Argentine',
                                            'ARM': 'Arménie',
                                            'ASM': 'Samoa américaines',
                                            'ATA': 'Antarctique',
                                            'ATF': 'Terres australes et antarctiques françaises',
                                            'ATG': 'Antigua-et-Barbuda',
                                            'AUS': 'Australie',
                                            'AUT': 'Autriche',
                                            'AZE': 'Azerbaidjan',
                                            'BDI': 'Burundi',
                                            'BEL': 'Belgique',
                                            'BEN': 'Benin',
                                            'BES': 'Pays-Bas caribéens',
                                            'BFA': 'Burkina Faso',
                                            'BGD': 'Bangladesh',
                                            'BGR': 'Bulgarie',
                                            'BHR': 'Bahrein',
                                            'BHS': 'Bahamas',
                                            'BIH': 'Bosnie-Herzegovine',
                                            'BLM': 'Saint-Barthélemy',
                                            'BLR': 'Bielorussie',
                                            'BLZ': 'Belize',
                                            'BMU': 'Bermudes',
                                            'BOL': 'Bolivie',
                                            'BRA': 'Brésil',
                                            'BRB': 'Barbade',
                                            'BRN': 'Brunei',
                                            'BTN': 'Bhoutan',
                                            'BWA': 'Botswana',
                                            'CAF': 'République Centrafricaine',
                                            'CAN': 'Canada',
                                            'CCK': 'Îles Cocos',
                                            'CHE': 'Suisse',
                                            'CHL': 'Chili',
                                            'CHN': 'Chine',
                                            'CIV': "Côte d'Ivoire",
                                            'CMR': 'Cameroun',
                                            'COD': 'Congo (République démocratique)',
                                            'COG': 'Congo (République)',
                                            'COK': 'Îles Cook',
                                            'COL': 'Colombie',
                                            'COM': 'Comores',
                                            'CPV': 'Cap-Vert',
                                            'CRI': 'Costa Rica',
                                            'CUB': 'Cuba',
                                            'CUW': 'Curaçao',
                                            'CXR': 'Île Christmas',
                                            'CYM': 'Caimans',
                                            'CYP': 'Chypre',
                                            'CZE': 'Tchéquie',
                                            'DEU': 'Allemagne',
                                            'DJI': 'Djibouti',
                                            'DMA': 'Dominique',
                                            'DNK': 'Danemark',
                                            'DOM': 'République dominicaine',
                                            'DZA': 'Algérie',
                                            'ECU': 'Equateur',
                                            'EGY': 'Egypte',
                                            'ERI': 'Erythrée',
                                            'ESH': 'Sahara occidental',
                                            'ESP': 'Espagne',
                                            'EST': 'Estonie',
                                            'ETH': 'Ethiopie',
                                            'FIN': 'Finlande',
                                            'FJI': 'Fidji',
                                            'FLK': 'Îles Malouines',
                                            'FRA': 'France',
                                            'FRO': 'Féroé',
                                            'FSM': 'Micronésie',
                                            'GAB': 'Gabon',
                                            'GBR': 'Royaume-Uni',
                                            'GEO': 'Géorgie',
                                            'GGY': 'Guernesey',
                                            'GHA': 'Ghana',
                                            'GIB': 'Gibraltar',
                                            'GIN': 'Guinée',
                                            'GLP': 'Guadeloupe',
                                            'GMB': 'Gambie',
                                            'GNB': 'Guinée-Bissau',
                                            'GNQ': 'Guinée équatoriale',
                                            'GRC': 'Grèce',
                                            'GRD': 'Grenade',
                                            'GRL': 'Groenland',
                                            'GTM': 'Guatemala',
                                            'GUF': 'Guyane',
                                            'GUM': 'Guam',
                                            'GUY': 'Guyana',
                                            'HKG': 'Hong Kong',
                                            'HND': 'Honduras',
                                            'HRV': 'Croatie',
                                            'HTI': 'Haïti',
                                            'HUN': 'Hongrie',
                                            'IDN': 'Indonésie',
                                            'IMN': 'Île de Man',
                                            'IND': 'Inde',
                                            'IOT': "Territoire britannique de l'océan Indien",
                                            'IRL': 'Irlande',
                                            'IRN': 'Irak',
                                            'IRQ': 'Iran',
                                            'ISL': 'Islande',
                                            'ISR': 'Israël',
                                            'ITA': 'Italie',
                                            'JAM': 'Jamaïque',
                                            'JEY': 'Jersey',
                                            'JOR': 'Jordanie',
                                            'JPN': 'Japon',
                                            'KAZ': 'Kazakhstan',
                                            'KEN': 'Kenya',
                                            'KGZ': 'Kirghizistan',
                                            'KHM': 'Cambodge',
                                            'KIR': 'Kiribati',
                                            'KNA': 'Saint-Christophe-et-Niévès',
                                            'KOR': 'Corée du Sud',
                                            'KWT': 'Koweït',
                                            'LAO': 'Laos',
                                            'LBN': 'Liban',
                                            'LBR': 'Liberia',
                                            'LBY': 'Libye',
                                            'LCA': 'Sainte-Lucie',
                                            'LIE': 'Liechtenstein',
                                            'LKA': 'Sri Lanka',
                                            'LSO': 'Lesotho',
                                            'LTU': 'Lituanie',
                                            'LUX': 'Luxembourg',
                                            'LVA': 'Lettonie',
                                            'MAC': 'Macao',
                                            'MAF': 'Sint-Maarten',
                                            'MAR': 'Maroc',
                                            'MCO': 'Monaco',
                                            'MDA': 'Moldavie',
                                            'MDG': 'Madagascar',
                                            'MDV': 'Maldives',
                                            'MEX': 'Mexique',
                                            'MHL': 'Marshall',
                                            'MKD': 'Macedoine',
                                            'MLI': 'Mali',
                                            'MLT': 'Malte',
                                            'MMR': 'Birmanie',
                                            'MNE': 'Monténégro',
                                            'MNG': 'Mongolie',
                                            'MNP': 'Îles Mariannes du Nord',
                                            'MOZ': 'Mozambique',
                                            'MRT': 'Mauritanie',
                                            'MSR': 'Montserrat',
                                            'MTQ': 'Martinique',
                                            'MUS': 'Maurice',
                                            'MWI': 'Malawi',
                                            'MYS': 'Malaisie',
                                            'MYT': 'Mayotte',
                                            'NAM': 'Namibie',
                                            'NCL': 'Nouvelle-Calédonie',
                                            'NER': 'Niger',
                                            'NFK': 'Île Norfolk',
                                            'NGA': 'Nigeria',
                                            'NIC': 'Nicaragua',
                                            'NIU': 'Niue',
                                            'NLD': 'Pays-Bas',
                                            'NOR': 'Norvège',
                                            'NPL': 'Nepal',
                                            'NRU': 'Nauru',
                                            'NZL': 'Nouvelle-Zélande',
                                            'OMN': 'Oman',
                                            'PAK': 'Pakistan',
                                            'PAN': 'Panama',
                                            'PCN': 'Îles Pitcairn',
                                            'PER': 'Pérou',
                                            'PHL': 'Philippines',
                                            'PLW': 'Palaos',
                                            'PNG': 'Papouasie-Nouvelle-Guinée',
                                            'POL': 'Pologne',
                                            'PRI': 'Porto Rico',
                                            'PRK': 'Corée du Nord',
                                            'PRT': 'Portugal',
                                            'PRY': 'Paraguay',
                                            'PSE': 'Palestine',
                                            'PYF': 'Polynésie française',
                                            'QAT': 'Qatar',
                                            'REU': 'Réunion',
                                            'ROU': 'Roumanie',
                                            'RUS': 'Russie',
                                            'RWA': 'Rwanda',
                                            'SAU': 'Arabie saoudite',
                                            'SDN': 'Soudan',
                                            'SEN': 'Sénégal',
                                            'SGP': 'Singapour',
                                            'SGS': 'Georgie du Sud-et-les iles Sandwich du Sud',
                                            'SHN': 'Sainte-Hélène, Ascension et Tristan da Cunha',
                                            'SJM': 'Svalbard et île Jan Mayen',
                                            'SLB': 'Salomon',
                                            'SLE': 'Sierra Leone',
                                            'SLV': 'Salvador',
                                            'SMR': 'Saint-Marin',
                                            'SOM': 'Somalie',
                                            'SPM': 'Saint-Pierre-et-Miquelon',
                                            'SRB': 'Serbie',
                                            'SSD': 'Soudan du Sud',
                                            'STP': 'Sao Tomé-et-Principe',
                                            'SUR': 'Suriname',
                                            'SVK': 'Slovaquie',
                                            'SVN': 'Slovénie',
                                            'SWE': 'Suède',
                                            'SWZ': 'eSwatani',
                                            'SXM': 'Saint-Martin ',
                                            'SYC': 'Seychelles',
                                            'SYR': 'Syrie',
                                            'TCA': 'Îles Turques-et-Caïques',
                                            'TCD': 'Tchad',
                                            'TGO': 'Togo',
                                            'THA': 'Thaïlande',
                                            'TJK': 'Tadjikistan',
                                            'TKL': 'Tokelau',
                                            'TKM': 'Turkmenistan',
                                            'TLS': 'Timor oriental',
                                            'TON': 'Tonga',
                                            'TTO': 'Trinité-et-Tobago',
                                            'TUN': 'Tunisie',
                                            'TUR': 'Turquie',
                                            'TUV': 'Tuvalu',
                                            'TWN': 'Taiwan',
                                            'TZA': 'Tanzanie',
                                            'UGA': 'Ouganda',
                                            'UKR': 'Ukraine',
                                            'URY': 'Uruguay',
                                            'USA': 'Etats-Unis',
                                            'UZB': 'Ouzbékistan',
                                            'VAT': 'Saint-Siège (État de la Cité du Vatican)',
                                            'VCT': 'Saint-Vincent-et-les-Grenadines',
                                            'VEN': 'Venezuela',
                                            'VGB': 'Îles Vierges britanniques',
                                            'VIR': 'Îles Vierges des États-Unis',
                                            'VNM': 'Viêt Nam',
                                            'VUT': 'Vanuatu',
                                            'WLF': 'Wallis-et-Futuna',
                                            'WSM': 'Samoa',
                                            'XKX': 'Kosovo',
                                            'YEM': 'Yémen',
                                            'ZAF': 'Afrique du Sud',
                                            'ZMB': 'Zambie',
                                            'ZWE': 'Zimbabwe',
                                            'NTZ': 'Zone neutre',
                                            'UNO': 'Fonctionnaire des Nations Unies',
                                            'UNA': "Fonctionnaire d'une organisation affiliée aux Nations Unies",
                                            'UNK': 'Représentant des Nations Unies au Kosovo',
                                            'XXA': 'Apatride Convention 1954',
                                            'XXB': 'Réfugié Convention 1954',
                                            'XXC': 'Réfugié autre',
                                            'XXX': 'Résident Légal de Nationalité Inconnue',
                                            'D': 'Allemagne',
                                            'EUE': 'Union Européenne',
                                            'GBD': "Citoyen Britannique d'Outre-mer (BOTC)",
                                            'GBN': 'British National (Overseas)',
                                            'GBO': 'British Overseas Citizen',
                                            'GBP': 'British Protected Person',
                                            'GBS': 'British Subject',
                                            'XBA': 'Banque Africaine de Développement',
                                            'XIM': "Banque Africaine d'Export–Import",
                                            'XCC': 'Caribbean Community or one of its emissaries',
                                            'XCO': 'Common Market for Eastern and Southern Africa',
                                            'XEC': 'Economic Community of West African States',
                                            'XPO': 'International Criminal Police Organization',
                                            'XOM': 'Sovereign Military Order of Malta',
                                            'RKS': 'Kosovo',
                                            'WSA': 'World Service Authority World Passport'
                                        }
}

## ENGLISH LANGUAGE

english = \
{
"Please type a MRZ or open a scan"  :   "Please type a MRZ or open a scan",
"Changelog : update summary"        :   "Changelog : update summary",
"Program version"                   :   "Program version",
"CNIRevelator Fatal Error"          :   "CNIRevelator Fatal Error" ,
"An error has occured"              :   "An error has occured",
"Downloading"                       :   "Downloading",
"Successful retrieved"              :   "Successful retrieved",
"Choose the identity document"      :   "Choose the identity document" ,
"OCR Detection Validation"          :   "OCR Detection Validation",
"Validate"                          :   "Validate",
"Validation Error"                  :   "Validation Error",
"The submitted MRZ contains invalid "
 "characters"                       :   "The submitted MRZ contains invalid characters",
"Connection"                        :   "Connection",
"Password"                          :   "Password",
"Booting up..."                     :   "Booting up...",
"CNIRevelator Fatal Eror"           :   "CNIRevelator Fatal Eror",
"CNIRevelator crashed because a "
"fatal error occured. View log for "
"more infos and please open "
"an issue on Github"                :   "CNIRevelator crashed because a fatal error occured. View log for more infos and please open an issue on Github",
"Would you like to open an issue "
"on Github to report this bug ?"    :   "Would you like to open an issue on Github to report this bug ?",
"Would you like to open the "
"log file ?"                        :   "Would you like to open the log file ?",
"Starting..."                       :   "Starting...",
"Informations about the current "
"document"                          :   "Informations about the current document",
"IDLE"                              :   "IDLE",
"Status"                            :   "Status",
"Name"                              :   "Name",
"Birth date"                        :   "Birth date",
"Issue date"                        :   "Issue date",
"Expiration date"                   :   "Issue date",
"Sex"                               :   "Sex",
"Issuing country"                   :   "Issuing country",
"Nationality"                       :   "Nationality",
"Registration"                      :   "Registration",
"Document number"                   :   "Document number",
"Unknown"                           :   "Unknown",
"Display and processing of "
"documents"                         :   "Display and processing of documents",
"Complete MRZ capture terminal"     :   "Complete MRZ capture terminal",
"Quick entry terminal (731)"        :   "Quick entry terminal (731)",
"Monitor"                           :   "Monitor",
"New"                               :   "New",
"Open scan..."                      :   "Open scan...",
"Quit"                              :   "Quit",
"File"                              :   "File",
"Settings"                          :   "Settings",
"Keyboard commands"                 :   "Keyboard commands",
"Report a bug"                      :   "Report a bug",
"About CNIRevelator"                :   "About CNIRevelator",
"Help"                              :   "Help",
"OCR module error"                  :   "OCR module error",
"The OCR module located at {} "
"can not be found or corrupted. "
"It will be reinstalled at "
"the next run"                      :   "The OCR module located at {} can not be found or corrupted. It will be reinstalled at the next run",
"The Tesseract module "
"encountered a problem: {}"         :   "The Tesseract module encountered a problem: {}",
"Tesseract error : {}. "
"Will be reinstallated"             :   "Tesseract error : {}. Will be reinstallated",
"Document detected: {}\n"           :   "Document detected : {}\n",
"Document detected again: {}\n"     :   "Document detected again : {}\n",
"Character not accepted !\n"        :   "Character not accepted !\n",
"Open a scan of document..."        :   "Open a scan of document...",
"OpenCV error (image processing)"   :   "OpenCV error (image processing)",
"A critical error has occurred in "
"the OpenCV image processing "
"manager used by CNIRevelator, the "
"application will reset itself"     :   "A critical error has occurred in the OpenCV image processing manager used by CNIRevelator, the application will reset itself",

"ABOUT"                             :   'Software Version: CNIRevelator' + globs.verstring_full + '\n\n'
                                        "Copyright © 2018-2019 Adrien Bourmault (neox95)" + "\n\n"
                                        "CNIRevelator is free software: you have the right to modify and / or distribute it"
                                        "in the terms of the GNU General Public License as published by"
                                        "Free Software Foundation, version 3 or"
                                        "later." + "\n\n"
                                        "CNIRevelator is distributed in the hope of being useful, without however"
                                        "imply any guarantee of"
                                        "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE Refer to the"
                                        "GNU General Public License for more details about this."
                                        "\n\n"
                                        "You should have received a copy of the GNU General Public License"
                                        "with CNIRevelator, if this is not the case, take a look at <https://www.gnu.org/licenses/>."
                                        "\n\n"
                                        "The Tesseract 4.0 OCR module is subject to the 2004 Apache License."
                                        "\n\n"
                                        "Python libraries and the Anaconda 3 environment are subject to the BSD 2018-2019 license."
                                        "\n\n"
                                        "The source code for this program is available on Github at <https://github.com/neox95/CNIRevelator>. \n"
                                        "Its operation is in accordance with the standards and guidelines of ICAO document 9303 governing travel and identity documents." + '\n\n'
                                        "In case of problems or special request, open an issue or send an email to neox@os-k.eu! \n\n",


"KEYBHELP"                          :   "Fast entry terminal (731): \n\n"
                                        "Allowed characters: Alphanumeric uppercase and the character '<' No lowercase or special characters, otherwise the sum is set to zero \n\n"
                                        "Calculate Result:\t\t\tControl Right\n"
                                        "Copy:\t\t\t\tCtrl-C\n"
                                        "Paste:\t\t\t\tCtrl-V\n"
                                        "\n\n"
                                        "MRZ input terminal complete: \n\n"
                                        "Allowed characters: Alphanumeric uppercase and the character '<' No lowercase or special characters, otherwise the sum is set to zero \n\n"
                                        "Calculate Result:\t\t\tControl Right\n"
                                        "Complete field:\t\t\tTab button\n"
                                        "Copy:\t\t\t\tCtrl-C\n"
                                        "Paste:\t\t\t\tCtrl-V\n"
                                        "Force a new document detection:\tEchap\n",

"CHANGELOG"                         :   "Version 3.1.2 \nMinor update with the following progressions:\n- Upgrade Tesseract OCR to 5.0\n\n" + \
"Version 3.1.1 \nMinor update with the following progressions: \n- Fixed a severe bug in the update system\n\n" + \
"Version 3.1.0 \nMajor update with the following progressions: \n- Cosmetic modifications of the user interface \n- Stabilization of the changes made on the minor version 3.0 : user interface, OCR, VISA A and B, logging\n- Rationalization of the language system\n- Added update channels\n\n" + \
"Version 3.0.8 final\nCorrection: bug in the update system'\n\n" + \
"Version 3.0.6 \nMinor update with the following fixes:\n- Change in the appearance of the application launcher\n- Improvements to the interface, including stability\n- Added digital signature of the executable\n" + \
"Version 3.0.7 final\nMajor update with the following corrections: \n- Redesign of the user interface\n- OCR function integrated into the application with TIFF and JPEG support\n- Corrections of errors on the processing of VISA type A and B, as well as residence permits\n\n" + \
"Version 3.0.6 \nMinor update with the following fixes:\n- Change in the appearance of the application launcher\n- Improvements to the interface, including stability\n- Added digital signature of the executable\n" + \
"Version 3.0.5 \n Minor update with the following corrections: \n- Change of executable icon to reflect the major version change accomplished in 3.0\n\n" + \
"Version 3.0.4 \nMinor update with the following fixes:\n- Fixed a bug affecting the update system" + \
"Version 3.0.3 \nMinor update with the following corrections: \n- Fixed a bug affecting the changelog\n- Fixed an error with the Delete Back key and Deleted causing a data loss" + \
"Version 3.0.2 \nMinor update with the following corrections: \n- Change of executable icon\n- Fix of a bug affecting logging\n- Fix of a bug affecting document detection- And other minor modifications\n\n" + \
"Version 3.0.1 \nMajor update with the following corrections: \n- Renewal of the executable's digital signature- Improvement of the log presentation in case of error\n- Total overhaul of the source code and disobfuscation\n- Reliable HTTPS downloads with checksum\n- New input terminals : a fast (731) and a complete one\n- Improved document detection, possibility of finer choice and the following regressions:\n- Temporary deletion of the OCR reading function. Planned return for a next version",

"Document Review: {}\n\n"           :   "Document Review: {}\n\n",
"Checksum position {}: Lu {} VS "
"Calculated {} [facultative]\n"     :   "Checksum position {}: Read {} VS Calculated {} [facultative]\n",
"Checksum position {}: Lu {} VS "
"Calculated {}\n"                   :   "Checksum position {}: Read {} VS Calculated {}\n",
"COMPLIANT"                         :   "COMPLIANT",
"IMPROPER"                          :   "IMPROPER",
"Installing the updates"            :   "Installing the updates",
"Verifying download..."             :   "Verifying download...",
"Preparing installation..."         :   "Preparing installation...",
"Success !"                         :   "Success !",
"Launching the new version..."      :   "Launching the new version...",
"Credentials Error. No effective "
"update !"                          :   "Credentials Error. No effective update !",
"Deleting old version"              :   "Deleting old version",
'Software is up-to-date !'          :   "Software is up-to-date !",
"An error occured. "
"No effective update !"             :   "An error occured. No effective update !",
"Shortcut creation"                 :   "Shortcut creation",
"Would you like to create/update "
"the shortcut for CNIRevelator on "
"your desktop ?"                    :   "Would you like to create/update the shortcut for CNIRevelator on your desktop ?",
"The file you provided is not "
"found : {}"                        :   "The file you provided is not found : {}",
"Update options"                    :   "Update options",
"Language"                          :   "Language",
"Show Changelog"                    :   "Show the changelog",
"Please choose your language : "    :   "Please choose your language : ",
"Please choose your update "
"channel : "                        :   "Please choose your update channel : ",
"Passeport"                         :   "Passport",
"Carte-passeport"                   :   "Passport card",
"Titre d'identité/de voyage"        :   "Identity/travel document",
"Certificat de membre d'équipage"   :   "Crew member certificate",
"Visa de type A"                    :   "Type A visa",
"Visa de type B"                    :   "Type B visa",
"Carte de séjour"                   :   "Residence permit",
"Pièce d'identité/de voyage"        :   "Identity/travel document",
"Pièce d'identité FR"               :   "French Identity card",
"Permis de conduire"                :   "Driver License",
"The file you provided is not "
"valid : {}"                        :   "The file you provided is not valid : {}",

"LANDCODE2"                         :   {
                                            "AW": "Aruba",
                                            "AF": "Afghanistan",
                                            "AO": "Angola",
                                            "AI": "Anguilla",
                                            "AL": "Albania",
                                            "AD": "Andorra",
                                            "AE": "United Arab Emirates",
                                            "AR": "Argentina",
                                            "AM": "Armenia",
                                            "AS": "American Samoa",
                                            "QA": "Antarctic",
                                            "TF": 'French Southern and Antarctic Territories',
                                            "AG": 'Antigua and Barbuda',
                                            "TO": "Australia",
                                            "AT": "Austria",
                                            "AZ": "Azerbaidjan",
                                            "BI": "Burundi",
                                            "BE": "Belgium",
                                            "BJ": "Benin",
                                            "BQ": "Caribbean Netherlands",
                                            "BF": "Burkina Faso",
                                            "BD": "Bangladesh",
                                            "BG": "Bulgaria",
                                            "BH": "Bahrain",
                                            "BS": "Bahamas",
                                            "BA": "Bosnia and Herzegovina",
                                            "BL": "Saint-Barthélemy",
                                            "BY": "Belarus",
                                            "BZ": "Belize",
                                            "BM": "Bermuda",
                                            "BO": "Bolivia",
                                            "BR": 'Brazil',
                                            "BB": "Barbados",
                                            "BN": "Brunei",
                                            "BT": "Bhutan",
                                            "BW": "Botswana",
                                            "CF": "Central African Republic",
                                            "CA": "Canada",
                                            "CC": "Cocos Islands",
                                            "CH": "Switzerland",
                                            "CL": "Chile",
                                            "CN": "China",
                                            "CI": "Côte d'Ivoire",
                                            "CM": "Cameroon",
                                            "CD": 'Congo (Democratic Republic)',
                                            "CG": "Congo (Republic)",
                                            "CK": "Cook Islands",
                                            "CO": "Colombia",
                                            "KM": "Comoros",
                                            "CV": "Cape Verde",
                                            "CR": "Costa Rica",
                                            "CU": "Cuba",
                                            "CW": "Curaçao",
                                            "CX": "Christmas Island",
                                            "KY": "Caimans",
                                            "CY": "Cyprus",
                                            "CZ": "Czech Republic",
                                            "DE": "Germany",
                                            "DJ": "Djibouti",
                                            "DM": "Dominique",
                                            "DK": "Denmark",
                                            "DO": 'Dominican Republic',
                                            "DZ": "Algeria",
                                            "EC": "Ecuador",
                                            "EG": "Egypt",
                                            "ER": "Eritrea",
                                            "EH": "Western Sahara",
                                            "ES": "Spain",
                                            "EE": "Estonia",
                                            "AND": "Ethiopia",
                                            "FI": "Finland",
                                            "FJ": "Fiji",
                                            "FK": "Falkland Islands",
                                            "FR": "France",
                                            "FO": "Faroese",
                                            "FM": "Micronesia",
                                            "GA": "Gabon",
                                            "GB": "United Kingdom",
                                            "GE": "Georgia",
                                            "GG": "Guernsey",
                                            "GH": "Ghana",
                                            "GI": "Gibraltar",
                                            "GN": "Guinea",
                                            "GP": "Guadeloupe",
                                            "GM": "Gambia",
                                            "GW": "Guinea-Bissau",
                                            "GQ": "Equatorial Guinea",
                                            "GR": "Greece",
                                            "GD": "Granada",
                                            "GL": "Greenland",
                                            "GT": "Guatemala",
                                            "GF": "Guyana",
                                            "GU": "Guam",
                                            "GY": "Guyana",
                                            "HK": "Hong Kong",
                                            "HN": "Honduras",
                                            "HR": "Croatia",
                                            "HT": "Haiti",
                                            "HU": "Hungary",
                                            "ID": "Indonesia",
                                            "IM": "Isle of Man",
                                            "IN": "India",
                                            "IO": 'British Indian Ocean Territory',
                                            "IE": "Ireland",
                                            "IR": "Iraq",
                                            "IQ": "Iran",
                                            "IS": "Iceland",
                                            "IL": "Israel",
                                            "IT": "Italy",
                                            "JM": "Jamaica",
                                            "I":  "Jersey",
                                            "JO": "Jordan",
                                            "JP": "Japan",
                                            "KZ": "Kazakhstan",
                                            "KE": "Kenya",
                                            "KG": "Kyrgyzstan",
                                            "KH": "Cambodia",
                                            "KI": "Kiribati",
                                            "KN": "Saint Kitts and Nevis",
                                            "KR": "South Korea",
                                            "KW": "Kuwait",
                                            "LA": "Laos",
                                            "LB": "Lebanon",
                                            "LR": "Liberia",
                                            "LY": "Libya",
                                            "LC": "Saint Lucia",
                                            "LI": "Liechtenstein",
                                            "LK": "Sri Lanka",
                                            "LS": "Lesotho",
                                            "LT": "Lithuania",
                                            "LU": "Luxembourg",
                                            "LV": "Latvia",
                                            "MO": "Macao",
                                            "MF": "Sint-Maarten",
                                            "MA": "Morocco",
                                            "MC": "Monaco",
                                            "MD": 'Moldavia',
                                            "MG": "Madagascar",
                                            "MV": "Maldives",
                                            "MX": "Mexico",
                                            "MH": "Marshall",
                                            "MK": "Macedonia",
                                            "ML": "Mali",
                                            "MT": "Malta",
                                            "MM": "Burma",
                                            "ME": "Montenegro",
                                            "MN": "Mongolia",
                                            "MP": "Northern Mariana Islands",
                                            "MZ": "Mozambique",
                                            "MR": "Mauritania",
                                            "MS": "Montserrat",
                                            "MQ": "Martinique",
                                            "MU": "Mauritius",
                                            "MW": "Malawi",
                                            "MY": "Malaysia",
                                            "YT": "Mayotte",
                                            "NA": "Namibia",
                                            "NC": "New Caledonia",
                                            "NE": "Niger",
                                            "NF": "Norfolk Island",
                                            "NG": "Nigeria",
                                            "NI": "Nicaragua",
                                            "NU": "Niue",
                                            "NL": 'Netherlands',
                                            "NO": "Norway",
                                            "NP": "Nepal",
                                            "NR": "Nauru",
                                            "NZ": "New Zealand",
                                            "OM": "Oman",
                                            "PK": "Pakistan",
                                            "PA": "Panama",
                                            "NP": "Pitcairn Islands",
                                            "PE": "Peru",
                                            "PH": "Philippines",
                                            "PW": "Palau",
                                            "PG": "Papua New Guinea",
                                            "PL": "Poland",
                                            "PR": "Puerto Rico",
                                            "KP": "North Korea",
                                            "PT": "Portugal",
                                            "PY": "Paraguay",
                                            "PS": "Palestine",
                                            "FP": "French Polynesia",
                                            "QA": "Qatar",
                                            "RE": "Reunion",
                                            "RO": "Romania",
                                            "RU": "Russia",
                                            "RW": "Rwanda",
                                            "SA": "Saudi Arabia",
                                            "SD": "Sudan",
                                            "SN": "Senegal",
                                            "SG": "Singapore",
                                            "GS": "South Georgia and the South Sandwich Islands",
                                            'SH': 'St Helena, Ascension and Tristan da Cunha',
                                            "SJ": "Svalbard and Jan Mayen Island",
                                            "SB": "Solomon",
                                            "SL": "Sierra Leone",
                                            "SV": "El Salvador",
                                            "SM": "San Marino",
                                            "SO": "Somalia",
                                            "PM": "Saint-Pierre-et-Miquelon",
                                            "RS": "Serbia",
                                            "SS": "South Sudan",
                                            "ST": "Sao Tome and Principe",
                                            "SR": "Suriname",
                                            "SK": "Slovakia",
                                            "SI": "Slovenia",
                                            "SE": "Sweden",
                                            "SZ": "eSwatani",
                                            "SX": "Saint-Martin",
                                            "SC": "Seychelles",
                                            "SY": "Syria",
                                            "TC": "Turks and Caicos Islands",
                                            "TD": "Chad",
                                            "TG": "Togo",
                                            "TH": "Thailand",
                                            "TJ": "Tajikistan",
                                            "TK": "Tokelau",
                                            "TM": "Turkmenistan",
                                            "TL": "East Timor",
                                            "TO": "Tonga",
                                            "TT": "Trinidad and Tobago",
                                            "TN": "Tunisia",
                                            "TR": "Turkey",
                                            "TV": "Tuvalu",
                                            "TW": "Taiwan",
                                            "TZ": "Tanzania",
                                            "UG": "Uganda",
                                            "UA": "Ukraine",
                                            "UY": "Uruguay",
                                            "US": "United States",
                                            "UZ": "Uzbekistan",
                                            'VA': 'Holy See (Vatican City State)',
                                            'VC': 'Saint Vincent and the Grenadines',
                                            "EV": "Venezuela",
                                            "VG": "British Virgin Islands",
                                            'VI': 'Virgin Islands of the United States',
                                            "VN": "Vietnam",
                                            "VU": "Vanuatu",
                                            "WF": "Wallis and Futuna",
                                            'WS': 'Samoa',
                                            "XK": "Kosovo",
                                            "YE": "Yemen",
                                            "ZA": "South Africa",
                                            "ZM": "Zambia",
                                            "ZW": "Zimbabwe"
                                        },

"LANDCODE3"                         :   {
                                            "ABW": "Aruba",
                                            "AFG": "Afghanistan",
                                            "OGM": "Angola",
                                            "AIA": "Anguilla",
                                            'ALB': 'Albania',
                                            "AND": "Andorra",
                                            "AER": "United Arab Emirates",
                                            "ARG": "Argentina",
                                            "ARM": "Armenia",
                                            "ASM": "American Samoa",
                                            "ATA": "Antarctica",
                                            'ATF': 'French Southern and Antarctic Lands',
                                            "ATG": "Antigua and Barbuda",
                                            "AUS": "Australia",
                                            "AUT": "Austria",
                                            "AZE": "Azerbaidjan",
                                            "BDI": "Burundi",
                                            "BEL": "Belgium",
                                            "BEN": "Benin",
                                            'BES': 'Caribbean Netherlands',
                                            "BFA": "Burkina Faso",
                                            "BGD": "Bangladesh",
                                            "BGR": "Bulgaria",
                                            "BHR": "Bahrain",
                                            "BHS": "Bahamas",
                                            "BIH": "Bosnia and Herzegovina",
                                            "BLM": "Saint-Barthélemy",
                                            "BLR": "Belarus",
                                            "BLZ": "Belize",
                                            "BMU": "Bermuda",
                                            "BOL": "Bolivia",
                                            "BRA": "Brazil",
                                            'BRB': 'Barbados',
                                            "BRN": "Brunei",
                                            "BTN": "Bhutan",
                                            "BWA": "Botswana",
                                            'CAF': 'Central African Republic',
                                            'CAN': 'Canada',
                                            "CCK": "Cocos Islands",
                                            "CHE": "Switzerland",
                                            "CHL": "Chile",
                                            "CHN": "China",
                                            'CIV': "Côte d'Ivoire",
                                            "CMR": "Cameroon",
                                            'COD': 'Congo (Democratic Republic)',
                                            "COG": "Congo (Republic)",
                                            "COK": "Cook Islands",
                                            "COL": "Colombia",
                                            "COM": "Comoros",
                                            'CPV': 'Cape Verde',
                                            "CRI": "Costa Rica",
                                            "CUB": "Cuba",
                                            "CUW": "Curaçao",
                                            "CXR": "Christmas Island",
                                            "CYM": "Caimans",
                                            "CYP": "Cyprus",
                                            "CZE": "Czech Republic",
                                            "DEU": "Germany",
                                            "DJI": "Djibouti",
                                            "DMA": "Dominique",
                                            "DNK": "Denmark",
                                            "DOM": "Dominican Republic",
                                            "DZA": "Algeria",
                                            'ECU': 'Ecuador',
                                            "EGY": "Egypt",
                                            "ERI": "Eritrea",
                                            'ESH': 'Western Sahara',
                                            "ESP": "Spain",
                                            "EST": "Estonia",
                                            "ETH": "Ethiopia",
                                            "FIN": "Finland",
                                            "FJI": "Fiji",
                                            "FLK": "Falkland Islands",
                                            "FRA": "France",
                                            "FRO": "Faroese",
                                            "WSF": "Micronesia",
                                            "ATM": "Gabon",
                                            "GBR": "United Kingdom",
                                            "GEO": "Georgia",
                                            "GGY": "Guernsey",
                                            "GHA": "Ghana",
                                            "GIB": "Gibraltar",
                                            "GIN": "Guinea",
                                            "GLP": "Guadeloupe",
                                            "GMB": "Gambia",
                                            "GNB": "Guinea-Bissau",
                                            "GNQ": "Equatorial Guinea",
                                            "GRC": "Greece",
                                            "DSO": "Granada",
                                            "GRL": "Greenland",
                                            "GTM": "Guatemala",
                                            'GUF': 'Guyana',
                                            "GUM": "Guam",
                                            "GUY": "Guyana",
                                            "HKG": "Hong Kong",
                                            "HND": "Honduras",
                                            "HRV": "Croatia",
                                            "HTI": "Haiti",
                                            "HUN": "Hungary",
                                            "IDN": "Indonesia",
                                            "IMN": "Isle of Man",
                                            "IND": "India",
                                            'IOT': 'British Indian Ocean Territory',
                                            "IRL": "Ireland",
                                            "IRN": "Iraq",
                                            "IRQ": "Iran",
                                            "ISL": "Iceland",
                                            "SRI": "Israel",
                                            "ITA": "Italy",
                                            "JAM": "Jamaica",
                                            "JEY": "Jersey",
                                            "JOR": "Jordan",
                                            'JPN': 'Japan',
                                            "KAZ": "Kazakhstan",
                                            "KEN": "Kenya",
                                            "KGZ": "Kyrgyzstan",
                                            "KHM": "Cambodia",
                                            "KIR": "Kiribati",
                                            "KNA": "Saint Kitts and Nevis",
                                            "KOR": "South Korea",
                                            "KWT": "Kuwait",
                                            "LAO": "Laos",
                                            "LBN": "Lebanon",
                                            "LBR": "Liberia",
                                            "LBY": "Libya",
                                            "LCA": "Saint Lucia",
                                            "LEL": "Liechtenstein",
                                            "LKA": "Sri Lanka",
                                            "LSO": "Lesotho",
                                            "LTU": "Lithuania",
                                            "LUX": "Luxembourg",
                                            "LVA": "Latvia",
                                            "MAC": "Macao",
                                            "MAF": "Sint-Maarten",
                                            "MAR": "Morocco",
                                            "MCO": "Monaco",
                                            "MDA": "Moldavia",
                                            "MDG": "Madagascar",
                                            "MDV": "Maldives",
                                            "MEX": "Mexico",
                                            "MHL": "Marshall",
                                            "MKD": "Macedonia",
                                            "MLI": "Mali",
                                            "MLT": "Malta",
                                            "MMR": "Burma",
                                            "MNE": "Montenegro",
                                            "MNG": "Mongolia",
                                            'MNP': 'Northern Mariana Islands',
                                            "MOZ": "Mozambique",
                                            "MRT": "Mauritania",
                                            "MSR": "Montserrat",
                                            "MTQ": "Martinique",
                                            "MUS": "Mauritius",
                                            "MWI": "Malawi",
                                            "MYS": "Malaysia",
                                            "MYT": "Mayotte",
                                            "NAM": "Namibia",
                                            "NCL": "New Caledonia",
                                            "NER": "Niger",
                                            "NFK": "Norfolk Island",
                                            "NGA": "Nigeria",
                                            "NIC": "Nicaragua",
                                            "NIU": "Niue",
                                            'NLD': 'Netherlands',
                                            "NOR": "Norway",
                                            "NPL": "Nepal",
                                            "NRU": "Nauru",
                                            "NZL": "New Zealand",
                                            "OMN": "Oman",
                                            "PAK": "Pakistan",
                                            "PAN": "Panama",
                                            "PCN": "Pitcairn Islands",
                                            "PER": "Peru",
                                            "PHL": "Philippines",
                                            "PLW": "Palau",
                                            "PNG": "Papua New Guinea",
                                            "POL": "Poland",
                                            "PRI": "Puerto Rico",
                                            "PRK": "North Korea",
                                            "PRT": "Portugal",
                                            "PRY": "Paraguay",
                                            "PES": "Palestine",
                                            "PYF": "French Polynesia",
                                            "QAT": "Qatar",
                                            "REU": "Reunion",
                                            "ROU": "Romania",
                                            "RUS": "Russia",
                                            "RWA": "Rwanda",
                                            "UAA": "Saudi Arabia",
                                            "SDN": "Sudan",
                                            "SEN": "Senegal",
                                            "SGP": "Singapore",
                                            'SGS': 'South Georgia and the South Sandwich Islands',
                                            "SHN": "St Helena, Ascension and Tristan da Cunha",
                                            "SJM": "Svalbard and Jan Mayen Island",
                                            "SLB": "Solomon",
                                            "SLE": "Sierra Leone",
                                            "SLV": "El Salvador",
                                            "SMR": "San Marino",
                                            "SOM": "Somalia",
                                            "SPM": "Saint-Pierre-et-Miquelon",
                                            "SRB": "Serbia",
                                            "SSD": "South Sudan",
                                            "PTS": "Sao Tome and Principe",
                                            "SUR": "Suriname",
                                            "SVK": "Slovakia",
                                            "SVN": "Slovenia",
                                            "SWE": "Sweden",
                                            "SWZ": "eSwatani",
                                            "SXM": "Saint-Martin",
                                            "SYC": "Seychelles",
                                            "SYR": "Syria",
                                            "TCA": "Turks and Caicos Islands",
                                            "TCD": "Chad",
                                            "TGO": "Togo",
                                            "THA": "Thailand",
                                            "TJK": "Tajikistan",
                                            "TKL": "Tokelau",
                                            "TKM": "Turkmenistan",
                                            "TLS": "East Timor",
                                            "TON": "Tonga",
                                            'TTO': 'Trinidad and Tobago',
                                            "TUN": "Tunisia",
                                            "TUR": "Turkey",
                                            "TUV": "Tuvalu",
                                            "TWN": "Taiwan",
                                            "TZA": "Tanzania",
                                            "UGA": "Uganda",
                                            "UKR": "Ukraine",
                                            "URY": "Uruguay",
                                            "USA": "United States",
                                            "UZB": "Uzbekistan",
                                            'VAT': 'Holy See (Vatican City State)',
                                            'VCT': 'Saint Vincent and the Grenadines',
                                            "VEN": "Venezuela",
                                            'VGB': 'British Virgin Islands',
                                            'VIR': 'Virgin Islands of the United States',
                                            "VNM": "Vietnam",
                                            "STV": "Vanuatu",
                                            "WLF": "Wallis and Futuna",
                                            "WSM": "Samoa",
                                            "XKX": "Kosovo",
                                            "YEM": "Yemen",
                                            "ZAF": "South Africa",
                                            "ZMB": "Zambia",
                                            "ZWE": "Zimbabwe",
                                            'NTZ': 'Neutral Zone',
                                            'UNO': 'United Nations official',
                                            'UNA': "Staff member of a United Nations-affiliated organization",
                                            'UNK': 'United Nations Representative in Kosovo',
                                            'XXA': 'Stateless Person 1954 Convention',
                                            "XXB": "Refugee Convention 1954",
                                            "XXC": "Other refugee",
                                            'XXX': 'Legal Resident of Unknown Nationality',
                                            'D'  : 'Germany',
                                            "EUE": "European Union",
                                            "GBD": "British Overseas Citizen (BOTC)",
                                            "GBN": "British National (Overseas)",
                                            "GBO": "British Overseas Citizen",
                                            'GBP': 'British Protected Person',
                                            "GBS": "British Subject",
                                            'XBA': 'African Development Bank',
                                            'XIM': "African Export Import Bank",
                                            'XCC':' Caribbean Community or one of its emissaries',
                                            'XCO': 'Common Market for Eastern and Southern Africa',
                                            'XEC': 'Economic Community of West African States',
                                            'XPO': 'International Criminal Police Organization',
                                            'XOM': 'Sovereign Military Order of Malta',
                                            "RKS": "Kosovo",
                                            "WSA": "World Service Authority World Passport"
                                        }
}

## MAIN DICT
all = \
{
"fr" : french,
"en" : english
}


## Functions

def readLang():

    if os.path.isfile(globs.CNIRLangFile):
        with open(globs.CNIRLangFile, 'r') as (configFile):
            try:
                # Reading it
                globs.CNIRlang = configFile.read()
            except Exception as e:
                critical.crashCNIR()
                raise IOError(str(e))
    else:
        # Recreating the url file
        try:
            os.mkdir(globs.CNIRFolder + '\\config')
        except:
            pass

        with open(globs.CNIRLangFile, 'w') as (configFile):
            try:
                # Writing it
                configFile.write(globs.CNIRlang)
            except Exception as e:
                critical.crashCNIR()
                raise IOError(str(e))

def updateLang(choice):

    if os.path.isfile(globs.CNIRLangFile):
        with open(globs.CNIRLangFile, 'w') as (configFile):
            try:
                # Writing it
                globs.CNIRlang = choice
                configFile.write(choice)
            except Exception as e:
                critical.crashCNIR()
                raise IOError(str(e))
    else:
        # Recreating the url file
        try:
            os.mkdir(globs.CNIRFolder + '\\config')
        except:
            pass

        with open(globs.CNIRLangFile, 'w') as (configFile):
            try:
                # Writing it
                configFile.write(globs.CNIRlang)
            except Exception as e:
                critical.crashCNIR()
                raise IOError(str(e))